### ISSUE TITLE
Wrong repository address in brew tap

### ISSUE THREAD

**Issue by gudnm** [exaroth/gonote#2]
$ brew tap exaroth/gonode && brew install gonote
==> Tapping exaroth/gonode
Cloning into '/usr/local/Library/Taps/exaroth/homebrew-gonode'...
remote: Repository not found.
fatal: repository 'https://github.com/exaroth/homebrew-gonode/' not found
Error: Failure while executing: git clone https://github.com/exaroth/homebrew-gonode /usr/local/Library/Taps/exaroth/homebrew-gonode --config core.autocrlf=false --depth=1

**Comment by exaroth** [comment]
```
brew tap exaroth/gonode && brew install gonote
```

It should be `brew tap exaroth/gonote`

**Comment by gudnm** [comment]
Thanks, it works!
