### ISSUE TITLE
Honour the unix $EDITOR environment variable.

### ISSUE THREAD

**Issue by kenguest** [exaroth/gonote#4]
It would be useful for gonote to honour the unix $EDITOR environment variable to specify/determine which editor should be used (instead of using ~/.gonote.json).

**Comment by exaroth** [comment]
Good call, I think loading editor type from env makes more sense.

**Comment by exaroth** [comment]
Pull request added - [https://github.com/exaroth/gonote/pull/6](https://github.com/exaroth/gonote/pull/6)

**Comment by pataquets** [comment]
@kenguest: as #6 is in, can this issue be closed?

**Comment by kenguest** [comment]
Yes, I think it should be closed now given the fix is present in the last release.
