### ISSUE TITLE
Default editor

### ISSUE THREAD

**Issue by davmaz** [exaroth/gonote#5]
When I change the default editor in gonote.json it indeed loads sublime_text with a unique name. However when I save the file, it does not show up on the simplenotes site or in gonote list.
What am I missing?
Thanks!

**Comment by exaroth** [comment]
Hello, the gonote was meant to work mainly with terminal editors (vim, emacs etc.) not gui style ones. I'm using vim on daily basis and I wrote it mostly for my own needs which is command line environment, thus support for gui editors like Sublime Text is not on the roadmap at the moment.
